export const data = {
  errorCode: 0,
  errorMessage: '',
  data: [
    {
      id: '084303000107',
      id_prob: '98.78',
      name: 'TRẦN THỊ HỒNG PHÚC',
      name_prob: '99.72',
      dob: '03/10/2003',
      dob_prob: '98.97',
      sex: 'NỮ',
      sex_prob: '99.07',
      nationality: 'VIỆT NAM',
      nationality_prob: '98.55',
      home: 'NGỌC BIÊN, TRÀ CÚ, TRÀ VINH',
      home_prob: '99.98',
      address: '58A ĐƯỜNG 1C, BÌNH HƯNG HÒA A, BÌNH TÂN, TP HỒ CHÍ MINH',
      address_prob: '98.99',
      doe: '03/10/2028',
      doe_prob: '98.89',
      overall_score: '99.73',
      number_of_name_lines: '1',
      address_entities: {
        province: 'HỒ CHÍ MINH',
        district: 'BÌNH TÂN',
        ward: 'BÌNH HƯNG HÒA A',
        street: '58A ĐƯỜNG 1C',
      },
      type_new: 'cccd_chip_front',
      type: 'chip_front',
    },
  ],
};
